### ISSUE TITLE
[PE-D][Tester E] Sample data not loaded

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-4/tp#138]
Starting up the application without a storage `json` file did not trigger the sample data to be loaded, even though the event was logged in the terminal:

![image.png](https://raw.githubusercontent.com/teoyuqi/ped/main/files/a022d220-a630-4969-9d38-06b75e70b023.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: teoyuqi/ped#3

**Comment by qiaoen17** [comment]
Added sample data along with deletion of all Persons related class
