### ISSUE TITLE
[PE-D][Tester E] Editting a person without changing input is accepted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-4/tp#145]
It appears that the application indicates a successful edit without any changes as a valid input. Perhaps a warning could be given to let the users know that no changes were made instead.

![image.png](https://raw.githubusercontent.com/teoyuqi/ped/main/files/4d7da4c5-f010-4e5d-9df0-34f04e33655d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: teoyuqi/ped#5

**Comment by Dilysss** [comment]
fixed in UG

**Comment by Dilysss** [comment]
edited in UG
