### ISSUE TITLE
[PE-D][Tester A] Duplicate Person issue.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-4/tp#158]
![image.png](https://raw.githubusercontent.com/Eclipse-Dominator/ped/main/files/14c6c642-dc1e-4205-a073-9482ae56dc0d.png)

From testing, we can see there adding of person is case sensitive (1 and 3 above) which enables user to be able to have multiple entries of the same person by varying the capitalisation. 

From 1 and 2, there is an extra space between "Xiao" and "Li". A regular user can easily accidentally type and additional space or forgot about case sensitivity and it might result in the addition of duplicate entries.

A potential work around could be storing all names internally as fully lower case and use the internal name to check for duplicate entry as well as replacing "\s+" with " " to remove extra spaces found in between letters as well as to keep things consistent.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Eclipse-Dominator/ped#3

**Comment by Dilysss** [comment]
did PR
