### ISSUE TITLE
[PE-D][Tester A] Ability to edit address does not reformat the integers before storing.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-4/tp#176]
`editstu 2 a/000000000000000000000000000000000000000000000000` 

Consider this valid edit. I am expecting the result is changing the attendance to 0/10.
Instead, the chunks of 0s are directly treated as a string instead of truncating and simplifying the 0s which is the expected behavior if a tutor is using the app.

![image.png](https://raw.githubusercontent.com/Eclipse-Dominator/ped/main/files/1a3c5a6c-6c5f-40c8-b346-40aa07f51cf6.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Eclipse-Dominator/ped#9

**Comment by Dilysss** [comment]
updated ug
